server:
  port: 8081

eureka:
  client:
    enabled: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service Routes
        - id: auth-service-register
          uri: http://auth-service:8884
          predicates:
            - Path=/api/auth/register
          filters:
            - RewritePath=/api/auth/register, /api/auth/register

        - id: auth-service-login
          uri: http://auth-service:8884
          predicates:
            - Path=/api/auth/login
          filters:
            - RewritePath=/api/auth/login, /api/auth/login

        # User Service Routes
        - id: user-service
          uri: http://user-service:8881
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}

        # Book Service Routes
        - id: book-service
          uri: http://book-service:8880
          predicates:
            - Path=/api/books/**
          filters:
            - RewritePath=/api/books/(?<segment>.*), /api/books/${segment}

        # Loan Service Routes
        - id: loan-service
          uri: http://loan-service:8882
          predicates:
            - Path=/api/loans/**
          filters:
            - RewritePath=/api/loans/(?<segment>.*), /api/loans/${segment}