apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: l4yoos/library-book-service:latest
          ports:
            - containerPort: 8880
          env:
            - name: SERVER_PORT
              value: "8880"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: USER_SERVICE_URL
              value: "http://user-service:8881/api/users"
            - name: INTERNAL_API_KEY_HEADER_NAME
              valueFrom:
                secretKeyRef:
                  name: internal-api-key-secret
                  key: INTERNAL_API_KEY_HEADER_NAME
            - name: INTERNAL_API_KEY_VALUE
              valueFrom:
                secretKeyRef:
                  name: internal-api-key-secret
                  key: INTERNAL_API_KEY_VALUE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_MS
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_EXPIRATION_MS
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred