apiVersion: v1
kind: Service
metadata:
  name: loan-service
  labels:
    app: loan-service
spec:
  selector:
    app: loan-service
  ports:
    - protocol: TCP
      port: 8882
      targetPort: 8882
  type: ClusterIP