apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: notification-service
          image: l4yoos/library-notification-service:latest
          ports:
            - containerPort: 8883
          env:
            - name: SERVER_PORT
              value: "8883"
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: "my-kafka-cluster-kafka-brokers:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "notification-service-group"
            - name: USER_SERVICE_URL
              value: "http://user-service:8881/api/users"
            - name: BOOK_SERVICE_URL
              value: "http://book-service:8880/api/books"
            - name: RESEND_SENDER_EMAIL
              value: "onboarding@resend.dev"
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: resend-api-key-secret
                  key: RESEND_API_KEY
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"