server:
  port: 8881

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.library.userservice
  paths-to-match: /**
  show-actuator: true
  info:
    title: User Service API
    version: 1.0.0
    description: API for managing book users in the Library System.
    termsOfService: http://swagger.io/terms/
    contact:
      name: L4yoos
      email: daleckikonrad1@gmail.com
    license:
      name: Apache 2.0
      url: http://springdoc.org

management:
  endpoint:
    prometheus:
      enabled: true