name: Auth Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-ci.yml'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --debug

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Auth Service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: auth-service/Dockerfile
          target: auth-service-run
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/library-auth-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max